### ISSUE TITLE
Is the "sustainability score" going the wrong way?

### ISSUE THREAD

**Issue by katrinabarlow** [thomaswilburn/powerhouse-demo#1]
Right now, the higher the score, the worse the sustainability measure. To indicate increasing sensitivity then, you lower your own threshold number.

Does it seems like it's backward - would it make more sense for the sustainability score to go up with more renewable energy, and down with more fossil fuels?

**Comment by thomaswilburn** [comment]
Well, that's true, but that's because it's not a sustainability score right now. The scoring from your sheet is really more of an UNsustainability measure in terms of environmental impact (I also like "Doom Points" as a metric). We can reverse that if you think it makes sense--it's not like we're implementing a real algorithm yet.

**Comment by katrinabarlow** [comment]
True true. Which one makes more sense to you (ignoring how i've set up the sheet so far!)?

**Comment by thomaswilburn** [comment]
My initial instinct is to say that since most people think about power in terms of carbon output (to the extent that most people think about it at all), it makes sense to basically score your power in terms of how "dirty" it is. It also relates to price a bit that way--I only want to use power when it's "cheap" in terms of how much it hurts the ecosystem.

I think you can make an argument that a sustainability score is easier to think about in terms of setting the threshold, as long as you introduce it and communicate it that way. But since I was introduced through your sheet, I've been primed the other way. Maybe a good thing to ask someone fresh?

**Comment by katrinabarlow** [comment]
Let's keep it this direction. I am relabeling it "carbon score," which I think makes it clear that higher is bad.
